# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ReduceByKey
email: me@yuan-shuai.info
description: A journey in the Data Science universe
baseurl: "" 
url: "http://technical.yuan-shuai.info"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
highlighter: rouge
